---

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
    scope: user

- name: xsession reload
  systemd:
    name: xsession-reload.service
    state: started
    scope: user
  failed_when: false

- name: restart pulseaudio
  systemd:
    name: pulseaudio.service
    state: restarted
    scope: user
  failed_when: false
