---

- name: icon default settings directory
  file:
    path: ~/.icons/default
    state: directory

- name: default system icon theme
  template:
    src: icons/icon.theme.j2
    dest: ~/.icons/default/index.theme
