---

- name: rofi config directory
  file:
    path: ~/.config/rofi
    state: directory

- name: rofi theme
  template:
    src: rofi/rofi.theme.j2
    dest: ~/.config/rofi/theme
    mode: 0755
  notify: xsession reload
