---

- name: bin directory
  file:
    path: ~/bin
    state: directory

- name: local bin directory
  file:
    path: ~/.local/bin/
    state: directory

- name: tmp directory
  file:
    path: ~/tmp
    state: directory

- name: binaries
  copy:
    src: bin/
    dest: ~/.local/bin/
    mode: 0755

- name: systemd user config directory
  file:
    path: ~/.config/systemd/user
    state: directory
