---
home_base_color_hue: 219
home_xft_dpi: 96
home_copy_pulseaudio_cookie: false
home_desktop: false
home_access_to_hosts: []
home_vnc_client_low_bandwidth: false
home_remote_workspace_config: false
home_vncserver_started_and_enabled: false
home_vncserver_display_number: 47
home_xsession_vncviewer: false

home_vncserver_allow_resize: true

home_vncserver_geometry: '1920x1200'

default_terminal: kitty
default_browser: firefox

# feature flags
with_activity: false

application_shortcuts:
  a: atom
  w: lowriter
  c: "{{calculator_command}}"
  i: loimpress
  d: lodraw
  s: xfce4-screenshooter
  l: catfish # search
  f: "{{file_browser_command}}" # files
  m: "{{mail_command}}"
  r: arandr

ssh_over_tor: false

system_suspend_command: systemctl suspend
system_reboot_command: systemctl reboot
system_poweroff_command: systemctl poweroff

xss_lock_enabled: true
lockscreen_lock_command: xset s activate
lockscreen_timeout: 300
lockscreen_locktime: 30

display_sleeptime: 300

file_browser_command: thunar
calculator_command: "{{default_browser}} --new-window https://www.geogebra.org/calculator"
mail_command: thunderbird

home_copy_all_background_images: false
background_image: background/eso0932a.jpg

home_autostart_terminal: false
home_autostart_nm_applet: false
home_autostart_blueman_applet: false
home_autostart_pasystray: false

home_autostart_unclutter: false

default_activities: []

workspaces: {}

font_family: Hack
font_size: 11
kitty_font_family: "{{font_family}}"
kitty_font_size: "{{font_size}}"
i3_font: "pango:{{font_family}} {{font_size}}"
i3_font_family: "{{font_family}}"
i3_font_size: "{{font_size}}"
xfce4_terminal_font: "{{font_family}} {{font_size}}"
xfce4_terminal_font_family: "{{font_family}}"
xfce4_terminal_font_size: "{{font_size}}"
rofi_font: "{{rofi_font_family}} {{rofi_font_size}}"
rofi_font_family: "{{font_family}}"
rofi_font_size: "{{font_size}}"

home_urxvt_font_pixelsize: "{{font_size}}"

home_xhosts_allow: []

pulseaudio_load_system_config: true
pulseaudio_jack_sink_enabled: false
pulseaudio_jack_sink_channels: 2
pulseaudio_jack_sink_client_name: PulseAudio
pulseaudio_jack_source_enabled: false
pulseaudio_jack_source_channels: 2
pulseaudio_jack_source_client_name: PulseAudio

todo_file: ~/todo.txt
