---
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
    scope: user

- name: xsession reload
  systemd:
    name: xsession-reload.service
    state: started
    scope: user
  failed_when: false

- name: reload i3
  shell: i3-msg reload
  when: i3_session is defined

- name: i3 reload
  shell: i3-msg reload  
  when: i3_session is defined
